QuanLyXe/Models/ThongtinDatxe.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongtinDatxe
    {
        public int MADX { get; set; }
        public int MATRANGTHAI { get; set; }
        public string TENTRANGTHAI { get; set; }
        public string TENDN { get; set; }
        public string HOTEN { get; set; }
        public Nullable<int> MAKHOA { get; set; }
        public string TENKHOA { get; set; }
        public int MALOAIXE { get; set; }
        public string TENLOAIXE { get; set; }
        public Nullable<int> MAXE { get; set; }
        public Nullable<System.DateTime> NGAYDX { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
        public Nullable<System.DateTime> NGAYVE { get; set; }
        public string GIODI { get; set; }
        public string GIOVE { get; set; }
        public string CHUTRIDOAN { get; set; }
        public Nullable<int> SOLUONGDOAN { get; set; }
        public string LOTRINHDI { get; set; }
        public string LOTRINHVE { get; set; }
        public Nullable<float> SOKMDI { get; set; }
        public Nullable<float> SOKMVE { get; set; }
        public string GHICHUDUYET { get; set; }
    }
}

QuanLyXe/Areas/Taixe/Controllers/DatxeTXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyXe.Models;

namespace QuanLyXe.Areas.Taixe.Controllers
{
    public class DatxeTXController : Controller
    {
        QUANLYXEEntities data = new QUANLYXEEntities();
        // GET: Taixe/DatxeTX
        public ActionResult Lichlamviec()
        {
            var user = (TAIXE)Session["User"];
            var pc = data.Phancongtxes.Where(n => n.TENDNTX == user.TENDNTX).OrderByDescending(n=>n.NGAYBATDAU).ToList();
            return View(pc);
        }

        public ActionResult Thongtindatxe()
        {
            var user = (TAIXE)Session["User"];
            var tt = data.spNgaylamtx(user.TENDNTX).OrderByDescending(n=>n.NGAYDI).ToList();
            return View(tt);
        }

        [HttpPost]
        public ActionResult Capnhat(int id)
        {
            var user = (TAIXE)Session["User"];
            var dx = data.DATXEs.SingleOrDefault(n => n.MADX == id);
            dx.MATRANGTHAI = 2;
            data.SaveChanges();
            var ttx = data.spNgaylamtx(user.TENDNTX).OrderByDescending(n => n.NGAYDI).ToList();
            return View("Thongtindatxe",ttx);
        }

        [HttpPost]
        public ActionResult CapnhatKT(int id)
        {
            var user = (TAIXE)Session["User"];
            var dx = data.DATXEs.SingleOrDefault(n => n.MADX == id);
            dx.MATRANGTHAI = 1;
            data.SaveChanges();
            var ttx = data.spNgaylamtx(user.TENDNTX).OrderByDescending(n => n.NGAYDI).ToList();
            return View("Thongtindatxe", ttx);
        }
    }
}

QuanLyXe/Areas/Taixe/Views/DatxeTX/Lichlamviec.cshtml
@model IEnumerable<QuanLyXe.Models.Phancongtx>

@{
    ViewBag.Title = "Lichlamviec";
    Layout = "~/Areas/Taixe/Views/Shared/_LayoutTaixe.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Lịch làm việc</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="#">Settings 1</a>
                        </li>
                        <li>
                            <a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                       
                        <th>Ngày bắt đầu</th>
                        <th>Ngày kết thúc</th>
                        <th>Mã xe</th>
                        <th>Nhãn hiệu</th>
                        <th>Biển số</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.NGAYBATDAU</td>
                            <td>@item.NGAYKETTHUC</td>
                            <td>@item.MAXE</td>
                            <td>@item.NHANHIEU</td>
                            <td>@item.BIENSO</td>
                        </tr>
                    }
                </tbody>
            </table>


        </div>
    </div>
</div>

QuanLyXe/Areas/Taixe/Views/DatxeTX/Thongtindatxe.cshtml
@model IEnumerable<QuanLyXe.Models.spNgaylamtx_Result>

@{
    ViewBag.Title = "Thongtindatxe";
    Layout = "~/Areas/Taixe/Views/Shared/_LayoutTaixe.cshtml";
}

@using (Html.BeginForm("Thongtindatxe", "DatxeTX"))
{
    <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Thông tin đặt xe</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="#">Settings 1</a>
                        </li>
                        <li>
                            <a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Tên tài xế</th>
                        <th>Ngày đi</th>
                        <th>Ngày về</th>
                        <th>Mã xe</th>
                        <th>Nhãn hiệu</th>
                        <th>Biển số</th>
                        <th>Trạng thái</th>
                        <th>Chọn</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.HOTENTX</td>
                            <td>@item.NGAYDI.Value.Day/@item.NGAYDI.Value.Month/@item.NGAYDI.Value.Year</td>
                            <td>@item.NGAYVE.Value.Day/@item.NGAYVE.Value.Month/@item.NGAYVE.Value.Year</td>
                            <td>@item.MAXE</td>
                            <td>@item.NHANHIEU</td>
                            <td>@item.BIENSO</td>
                            <td style="color:red" id="@item.MADX+tt">@item.TENTRANGTHAI</td>
                            <td>
                                @if (item.MATRANGTHAI == 3)
                                {
                                    <button class="btn btn-success" data-iddxtx="@item.MADX" id="LuuTT">Bắt đầu</button>
                                }
                                else
                                {
                                    <button class="btn btn-success" data-iddxtx="@item.MADX" id="LuuTT" disabled>Bắt đầu</button>
                                }
                                <button class="btn btn-danger" data-iddxtxkt="@item.MADX" id="LuuTTKT">Kết thúc</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>


        </div>
    </div>
</div>
}