QuanLyXe/Models/PHIKHAC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIKHAC
    {
        public int MAPHI { get; set; }
        public int MAXE { get; set; }
        public string NOIDUNGPHI { get; set; }
        public Nullable<decimal> TONGPHI { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public string NOITHUCHIEN { get; set; }
        public string HOADONPHI { get; set; }
    
        public virtual XE XE { get; set; }
    }
}

QuanLyXe/Models/SUACHUA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUACHUA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUACHUA()
        {
            this.CHITIETSUACHUAs = new HashSet<CHITIETSUACHUA>();
        }
    
        public int MASUACHUA { get; set; }
        public int MAXE { get; set; }
        public string NOISUA { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSUACHUA> CHITIETSUACHUAs { get; set; }
        public virtual XE XE { get; set; }
    }
}

QuanLyXe/Models/XANGLOP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XANGLOP
    {
        public int MAXANGLOP { get; set; }
        public int MAXE { get; set; }
        public string DIADIEM { get; set; }
        public Nullable<System.DateTime> NGAYDO { get; set; }
        public Nullable<float> SOLUONG { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string ANHHOADON { get; set; }
        public string LOAIHINH { get; set; }
    
        public virtual XE XE { get; set; }
    }
}

QuanLyXe/Controllers/SuachuaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyXe.Models;
using System.IO;
using QuanLyXe.DAO;

namespace QuanLyXe.Controllers
{
    public class SuachuaController : Controller
    {
        // GET: Suachua
        QUANLYXEEntities data = new QUANLYXEEntities();
        public ActionResult Xanglop()
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(15, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tt = data.XANGLOPs.OrderByDescending(n => n.NGAYDO).ToList();
            return View(tt);
        }

        public ActionResult Suachuax()
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(16, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tt = data.v_Suachua.OrderByDescending(n => n.NGAYKT).ToList();
            return View(tt);
        }

        public ActionResult Phikhac()
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(14, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tt = data.PHIKHACs.OrderByDescending(n => n.NGAYTHUCHIEN).ToList();
            return View(tt);
        }

        public ActionResult Themxanglop()
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(10, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            ViewBag.xe = new SelectList(data.XEs.ToList().OrderBy(n => n.MALOAIXE), "MAXE", "BIENSO");
            return View();
        }

        [HttpPost]
        public ActionResult Themxanglop(XANGLOP x, FormCollection fc, HttpPostedFileBase fileUpload)
        {
            ViewBag.xe = new SelectList(data.XEs.ToList().OrderBy(n => n.MALOAIXE), "MAXE", "BIENSO");

            x.NGAYDO = Convert.ToDateTime(fc["ngay"]);
            x.MAXE = Convert.ToInt32(fc["xe"]);


            if (fileUpload == null)
            {
                data.XANGLOPs.Add(x);
                data.SaveChanges();
                return RedirectToAction("Xanglop");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Hinhhoadon"), fileName);
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                        return View();
                    }
                    else
                    {
                        x.ANHHOADON = fileName;
                        data.XANGLOPs.Add(x);
                        data.SaveChanges();
                        fileUpload.SaveAs(path);
                    }
                }
                return RedirectToAction("Xanglop");
            }
        }


        public ActionResult Themphikhac()
        {
            var user = (USER)Session["USER"]; if (user == null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(12, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            ViewBag.xe = new SelectList(data.XEs.ToList().OrderBy(n => n.MALOAIXE), "MAXE", "BIENSO");
            return View();
        }

        [HttpPost]
        public ActionResult Themphikhac(PHIKHAC x, FormCollection fc, HttpPostedFileBase fileUpload)
        {
            ViewBag.xe = new SelectList(data.XEs.ToList().OrderBy(n => n.MALOAIXE), "MAXE", "BIENSO");

            x.NGAYTHUCHIEN = Convert.ToDateTime(fc["ngay"]);
            x.MAXE = Convert.ToInt32(fc["xe"]);


            if (fileUpload == null)
            {
                data.PHIKHACs.Add(x);
                data.SaveChanges();
                return RedirectToAction("Phikhac");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Hinhhoadon"), fileName);
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                        return View();
                    }
                    else
                    {
                        x.HOADONPHI = fileName;
                        data.PHIKHACs.Add(x);
                        data.SaveChanges();
                        fileUpload.SaveAs(path);
                    }
                }
                return RedirectToAction("Phikhac");
            }
        }
    }
}

QuanLyXe/Views/Suachua/Phikhac.cshtml
@model IEnumerable<QuanLyXe.Models.PHIKHAC>

@{
    ViewBag.Title = "Phikhac";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Thông tin xăng lốp</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="#">Settings 1</a>
                        </li>
                        <li>
                            <a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Địa điểm</th>
                        <th>Mã xe</th>
                        <th>Nội dung</th>
                        <th>Tổng tiền</th>
                        <th>Ngày thực hiện</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>@item.NOITHUCHIEN</td>
                            <td style="color:blue;font-weight:bold"><a href="@Url.Action("Chitietxe","Xe",new { id=item.MAXE })">@item.MAXE</a></td>
                            <td>@item.NOIDUNGPHI</td>
                            <td>@item.TONGPHI</td>
                            <td>@item.NGAYTHUCHIEN.Value.Day/@item.NGAYTHUCHIEN.Value.Month/@item.NGAYTHUCHIEN.Value.Year</td>
                        </tr>
                    }
                </tbody>
            </table>

            <hr />
        </div>
    </div>
</div>

QuanLyXe/Views/Suachua/Suachuax.cshtml
@model IEnumerable<QuanLyXe.Models.v_Suachua>

@{
    ViewBag.Title = "Suachuax";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Thông tin sửa chữa</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="#">Settings 1</a>
                        </li>
                        <li>
                            <a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Nơi sửa</th>
                        <th>Mã xe</th>
                        <th>Nội dung</th>
                        <th>Số lượng</th>
                        <th>Tổng tiền</th>
                        <th>Ngày bắt đầu</th>
                        <th>Ngày kết thúc</th>
                        <th>Ghi chú</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>@item.NOISUA</td>
                            <td style="color:blue;font-weight:bold"><a href="@Url.Action("Chitietxe","Xe",new { id=item.MAXE })">@item.MAXE</a></td>
                            <td>@item.NOIDUNGSC</td>
                            <td>@item.SOLUONGSC</td>
                            <td>@item.TONGTIENSC</td>
                            <td>@item.NGAYBD.Value.Day/@item.NGAYBD.Value.Month/@item.NGAYBD.Value.Year</td>
                            <td>@item.NGAYKT.Value.Day/@item.NGAYKT.Value.Month/@item.NGAYKT.Value.Year</td>
                            <td>@item.GHICHUSC</td>
                        </tr>
                    }
                </tbody>
            </table>

            <hr />
        </div>
    </div>
</div>

QuanLyXe/Views/Suachua/Themphikhac.cshtml
@model QuanLyXe.Models.PHIKHAC

@{
    ViewBag.Title = "Themphikhac";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@using (Html.BeginForm("Themphikhac", "Suachua", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Thêm phí khác</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-horizontal form-label-left input_mask">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Nội dung:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.EditorFor(model => model.NOIDUNGPHI, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NOIDUNGPHI, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Chọn xe:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.DropDownList("xe", null, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Địa điểm:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.EditorFor(model => model.NOITHUCHIEN, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NOITHUCHIEN, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Ngày thực hiện:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12 col-sm-10 col-xs-12">
                            <input class="date-picker form-control" name="ngay" required="required" type="date">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Tổng tiền:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.EditorFor(model => model.TONGPHI, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TONGPHI, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Hình hóa đơn(nếu có):</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <input type="file" name="fileUpload" />
                            <div style="color:red">@ViewBag.Thongbao</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10 col-sm-10 col-xs-12">
                            <button class="btn btn-primary" type="reset">Reset</button>
                            <input type="submit" value="Thêm" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLyXe/Views/Suachua/Themxanglop.cshtml
@model QuanLyXe.Models.XANGLOP

@{
    ViewBag.Title = "Themxanglop";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@using (Html.BeginForm("Themxanglop", "Suachua", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Thêm xăng lốp</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-horizontal form-label-left input_mask">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Nội dung:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.EditorFor(model => model.LOAIHINH, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LOAIHINH, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Chọn xe:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.DropDownList("xe", null, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Địa điểm:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.EditorFor(model => model.DIADIEM, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DIADIEM, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Ngày thực hiện:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12 col-sm-10 col-xs-12">
                            <input class="date-picker form-control" name="ngay" required="required" type="date">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Số lượng:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.EditorFor(model => model.SOLUONG, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SOLUONG, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Tổng tiền:</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            @Html.EditorFor(model => model.TONGTIEN, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TONGTIEN, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2 col-sm-2 col-xs-12">Hình hóa đơn(nếu có):</div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <input type="file" name="fileUpload" />
                            <div style="color:red">@ViewBag.Thongbao</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10 col-sm-10 col-xs-12">
                            <button class="btn btn-primary" type="reset">Reset</button>
                            <input type="submit" value="Thêm" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLyXe/Views/Suachua/Xanglop.cshtml
@model IEnumerable<QuanLyXe.Models.XANGLOP>

@{
    ViewBag.Title = "Xanglop";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Thông tin xăng lốp</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="#">Settings 1</a>
                        </li>
                        <li>
                            <a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Loại hình</th>
                        <th>Mã xe</th>
                        <th>Địa điểm</th>
                        <th>Ngày thực hiện</th>
                        <th>Số lượng</th>
                        <th>Tổng tiền</th>
                        <th>Hóa đơn</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>@item.LOAIHINH</td>
                            <td style="color:blue;font-weight:bold"><a href="@Url.Action("Chitietxe","Xe",new { id=item.MAXE })">@item.MAXE</a></td>
                            <td>@item.DIADIEM</td>
                            <td>@item.NGAYDO.Value.Day/@item.NGAYDO.Value.Month/@item.NGAYDO.Value.Year</td>
                            <td>@item.SOLUONG</td>
                            <td>@item.TONGTIEN</td>
                            <td>@item.ANHHOADON</td>
                        </tr>
                    }
                </tbody>
            </table>
            <hr />
        </div>
    </div>
</div>