QuanLyXe/Models/THONGKETHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKETHANG
    {
        public decimal THANG { get; set; }
        public decimal NAM { get; set; }
        public int MAXE { get; set; }
        public Nullable<int> SOCHUYEN { get; set; }
        public Nullable<float> SOKM { get; set; }
    
        public virtual XE XE { get; set; }
    }
}

QuanLyXe/Models/Thongtinxe.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongtinxe
    {
        public int MAXE { get; set; }
        public string BIENSO { get; set; }
        public string NHANHIEU { get; set; }
        public string TENLOAIXE { get; set; }
        public string HOPSO { get; set; }
        public string NHIENLIEU { get; set; }
        public string TENTINHTRANG { get; set; }
        public Nullable<System.DateTime> HANLUUHANH { get; set; }
        public Nullable<System.DateTime> HANBAOHIEM { get; set; }
        public string HINHXE { get; set; }
        public int MATINHTRANG { get; set; }
    }
}

QuanLyXe/Models/XE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.CHITIETPHANCONGs = new HashSet<CHITIETPHANCONG>();
            this.DATXEs = new HashSet<DATXE>();
            this.PHIKHACs = new HashSet<PHIKHAC>();
            this.SUACHUAs = new HashSet<SUACHUA>();
            this.THONGKETHANGs = new HashSet<THONGKETHANG>();
            this.XANGLOPs = new HashSet<XANGLOP>();
        }
    
        public int MAXE { get; set; }
        public int MALOAIXE { get; set; }
        public int MATINHTRANG { get; set; }
        public string BIENSO { get; set; }
        public string NHANHIEU { get; set; }
        public string HOPSO { get; set; }
        public string NHIENLIEU { get; set; }
        public Nullable<System.DateTime> HANLUUHANH { get; set; }
        public Nullable<System.DateTime> HANBAOHIEM { get; set; }
        public string HINHXE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHANCONG> CHITIETPHANCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATXE> DATXEs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIKHAC> PHIKHACs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUACHUA> SUACHUAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGKETHANG> THONGKETHANGs { get; set; }
        public virtual TINHTRANGXE TINHTRANGXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XANGLOP> XANGLOPs { get; set; }
    }
}

QuanLyXe/Controllers/XeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyXe.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
using QuanLyXe.DAO;
using Newtonsoft.Json;

namespace QuanLyXe.Controllers
{
    public class XeController : Controller
    {
        QUANLYXEEntities data = new QUANLYXEEntities();


        public ActionResult Thongtinxe(int? page)
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(5, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var pageNum = (page ?? 1);
                    var pageSize = 9;
                    DateTime dt = DateTime.Now;
                    var tt = data.sp_Xedadat(dt,dt).ToList();
            List<Tinhtrangsudungxe> ttsd = new List<Tinhtrangsudungxe>();
            foreach(var item in tt)
            {
                Tinhtrangsudungxe ttsdx = new Tinhtrangsudungxe(item.MAXE,item.BIENSO, item.NHANHIEU, item.TENTINHTRANG, item.TENTRANGTHAI, item.TENLOAIXE, item.NHIENLIEU, item.HOPSO, item.HINHXE);
                ttsd.Add(ttsdx);
            }
            var ttcd = data.sp_Xechuadat(dt, dt).ToList();
            foreach (var item in ttcd)
            {
                Tinhtrangsudungxe ttsdx = new Tinhtrangsudungxe(item.MAXE, item.BIENSO, item.NHANHIEU, item.TENTINHTRANG, item.TENTRANGTHAI, item.TENLOAIXE, item.NHIENLIEU, item.HOPSO, item.HINHXE);
                ttsd.Add(ttsdx);
            }

            return View(ttsd.OrderBy(n=>n._MAXE).ToPagedList(pageNum, pageSize));
        }

        public ActionResult Chitietxe(int id)
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(5, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tt = data.Thongtinxes.SingleOrDefault(n => n.MAXE == id);
            ViewBag.MaLX = new SelectList(data.LOAIXEs.ToList().OrderBy(n => n.MALOAIXE), "MALOAIXE", "TENLOAIXE",tt.MAXE);
            ViewBag.MaTT = new SelectList(data.TINHTRANGXEs.ToList().OrderBy(n => n.MATINHTRANG), "MATINHTRANG", "TENTINHTRANG",tt.MATINHTRANG);
            return View(tt);
        }

        [HttpPost]
        public ActionResult Chitietxe(int id, FormCollection fc, HttpPostedFileBase fileUpload)
        {
            var user = (USER)Session["USER"]; if (user == null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(6, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tt = data.XEs.SingleOrDefault(n => n.MAXE == id);
            ViewBag.MaLX = new SelectList(data.LOAIXEs.ToList().OrderBy(n => n.MALOAIXE), "MALOAIXE", "TENLOAIXE", tt.MAXE);
            ViewBag.MaTT = new SelectList(data.TINHTRANGXEs.ToList().OrderBy(n => n.MATINHTRANG), "MATINHTRANG", "TENTINHTRANG", tt.MATINHTRANG);

            tt.MAXE = Convert.ToInt32(fc["MaLX"]);
            tt.MATINHTRANG = Convert.ToInt32(fc["MaTT"]);

            if (fileUpload == null)
            {
                var tt1 = data.XEs.SingleOrDefault(n => n.MAXE == tt.MAXE);
                UpdateModel(tt1);
                data.SaveChanges();
                var tk = data.Thongtinxes.SingleOrDefault(n => n.MAXE == id);
                return View(tk);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Hinhxe"), fileName);
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.Thongbao = "Hình ảnh đã tồn tại";

                        var tk1 = data.Thongtinxes.SingleOrDefault(n => n.MAXE == id);
                        return View(tk1);
                    }
                    else
                    {

                        tt.HINHXE = fileName;

                        var tt1 = data.XEs.SingleOrDefault(n => n.MAXE == tt.MAXE);
                        UpdateModel(tt1);
                        data.SaveChanges();
                        fileUpload.SaveAs(path);
                    }
                }

                var tk = data.Thongtinxes.SingleOrDefault(n => n.MAXE == id);
                return View(tk);
            }
        }

        public ActionResult Thongkethang(int id)
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(5, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tk = data.sp_TKThang(DateTime.Now.Month, DateTime.Now.Year, id).SingleOrDefault();
            ViewBag.thang = tk.THANG;
            ViewBag.nam = tk.NAM;
            ViewBag.sochuyen = tk.SOCHUYEN;
            ViewBag.sokm = tk.SOKM;

            var cttk = data.sp_CTTKThang(id, DateTime.Now.Month).OrderBy(n=>n.NGAYDI).ToList();
            List<DataPoint> dataPoints = new List<DataPoint>();
            foreach (var item in cttk)
            {
                dataPoints.Add(new DataPoint("Ngày: "+Convert.ToString(item.NGAYDI.Value.Day+"-"+item.NGAYVE.Value.Day), Convert.ToDecimal(item.SOKMDI + item.SOKMVE)));
            }

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);

            return PartialView(tk);
        }

        public ActionResult Hoatdongganday(int id)
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(5, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var hd = data.v_DatxeTaixe.Where(n => n.MAXE == id && n.MATRANGTHAI == 1 && n.NGAYVE.Value.Month==DateTime.Now.Month).OrderByDescending(n => n.NGAYDI).ToList().Take(8);
                    return PartialView(hd);
        }

        public ActionResult ThongtinXanglop(int id)
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(5, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tt = data.XANGLOPs.Where(n => n.MAXE == id).OrderByDescending(n => n.NGAYDO).ToList().Take(8);
            return PartialView(tt);
        }

        public ActionResult ThongtinSuachua(int id)
        {

            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(5, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");

            var tt = data.v_Suachua.Where(n => n.MAXE == id).OrderByDescending(n => n.NGAYKT).ToList().Take(8);
            return PartialView(tt);
        }

        public ActionResult ThongtinPhikhac(int id)
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(5, user.TENDN);
            if (result == false)
                return RedirectToAction("Khongduocphep", "Home");
            

            var tt = data.PHIKHACs.Where(n => n.MAXE == id).OrderByDescending(n => n.NGAYTHUCHIEN).ToList().Take(8);
            return PartialView(tt);
        }

        public ActionResult Themxe()
        {
            var user = (USER)Session["USER"]; if(user==null) return RedirectToAction("Dangnhap", "Home");
            var result = new CheckRole().Kiemtraquyen(6, user.TENDN);
            if(result==false)
                return RedirectToAction("Khongduocphep", "Home");

            ViewBag.MaLX = new SelectList(data.LOAIXEs.ToList().OrderBy(n => n.MALOAIXE), "MALOAIXE", "TENLOAIXE");
            return View();

        }

        [HttpPost]
        public ActionResult Themxe(XE xe, FormCollection fc, HttpPostedFileBase fileUpload)
        {
            ViewBag.MaLX = new SelectList(data.LOAIXEs.ToList().OrderBy(n => n.MALOAIXE), "MALOAIXE", "TENLOAIXE");

            if (fileUpload == null)
            {
                ViewBag.Thongbao = "Vui lòng chọn ảnh bìa";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Hinhxe"), fileName);
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                        return View();
                    }
                    else
                    {

                        xe.HINHXE = fileName;

                        xe.MATINHTRANG = 1;
                        xe.MALOAIXE = Convert.ToInt32(fc["MaLX"]);
                        xe.HANBAOHIEM = Convert.ToDateTime(fc["hanbaohiem"]);
                        xe.HANBAOHIEM = Convert.ToDateTime(fc["hanluuhanh"]);
                        data.XEs.Add(xe);
                        data.SaveChanges();
                        fileUpload.SaveAs(path);
                    }
                }
                return RedirectToAction("Thongtinxe");
            }
        }


    }
}

QuanLyXe/Views/Xe/Chitietxe.cshtml
@model QuanLyXe.Models.Thongtinxe

@{
    ViewBag.Title = "Chitietxe";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Thông tin xe</h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Tìm</button>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Chi tiết</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="#">Settings 1</a>
                                </li>
                                <li>
                                    <a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                        <div class="profile_img">
                            <div id="crop-avatar">
                                <!-- Current avatar -->
                                <a href="~/Content/Hinhxe/@Model.HINHXE" target="_blank"><img class="img-responsive avatar-view" src="~/Content/Hinhxe/@Model.HINHXE" alt="Avatar" title="Change the avatar"></a>
                            </div>
                        </div>
                        <h3>Mã xe: @Model.MAXE | @Model.BIENSO</h3>

                        <ul class="list-unstyled user_data">
                            <li><i class="fa fa-automobile"></i> Nhãn hiệu: @Model.NHANHIEU @Model.TENLOAIXE</li>
                            <li><i class="fa fa-fire-extinguisher"></i> Nhiên liệu: @Model.NHIENLIEU</li>
                            <li><i class="fa fa-tachometer"></i> Hộp số: @Model.HOPSO</li>
                            <li><i class="fa fa-tachometer"></i> Tình trạng: @Model.TENTINHTRANG</li>
                            <li><i class="fa fa-calendar"></i> Hạn bảo hiểm: @Model.HANBAOHIEM.Value.Day/@Model.HANBAOHIEM.Value.Month/@Model.HANBAOHIEM.Value.Year</li>
                            <li><i class="fa fa-calendar"></i> Hạn lưu hành: @Model.HANLUUHANH.Value.Day/@Model.HANLUUHANH.Value.Month/@Model.HANLUUHANH.Value.Year</li>
                        </ul>

                        <button type="button" class="btn btn-success fa fa-edit m-right-xs" data-toggle="modal" data-target="#exampleModal">
                            Sửa thông tin
                        </button>
                        <br />
                        <!-- Modal -->
                        @using (Html.BeginForm("Chitietxe", "Xe", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Sửa</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">

                                            <div class="form-horizontal">
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.TENLOAIXE, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.DropDownList("MaLX", null, new { @class = "form-control" })
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.TENTINHTRANG, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.DropDownList("MaTT", null, new { @class = "form-control" })
                                                    </div>
                                                </div>    

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.BIENSO, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.BIENSO, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.BIENSO, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.NHANHIEU, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.NHANHIEU, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.NHANHIEU, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.HOPSO, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.HOPSO, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.HOPSO, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.NHIENLIEU, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.NHIENLIEU, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.NHIENLIEU, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.HANBAOHIEM, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.HANBAOHIEM, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.HANBAOHIEM, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.HANLUUHANH, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.HANLUUHANH, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.HANLUUHANH, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.HINHXE, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        <input type="file" name="fileUpload" />
                                                        <div style="color:red">@ViewBag.Thongbao</div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        <!-- start skills -->
                        <!-- end of skills -->

                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">

                        <div class="profile_title">
                            <div class="col-md-6">
                                <h2>Hoạt động</h2>
                            </div>
                        </div>
                        <!-- start of user-activity-graph -->
                        @Html.Action("Thongkethang", "Xe")
                        <!-- end of user-activity-graph -->

                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Hoạt động gần đây</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Chi phí sửa chữa gần đây</a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">

                                    <!-- start recent activity -->
                                    @Html.Action("Hoatdongganday", "Xe")
                                    <!-- end recent activity -->

                                </div>
                                <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">

                                    <!-- start user projects -->
                                    @Html.Action("ThongtinXanglop", "Xe")
                                    @Html.Action("ThongtinSuachua", "Xe")
                                    @Html.Action("ThongtinPhikhac", "Xe")
                                    <!-- end user projects -->

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QuanLyXe/Views/Xe/Hoatdongganday.cshtml
@model IEnumerable<QuanLyXe.Models.v_DatxeTaixe>

@foreach (var item in Model)
{

    <ul class="messages">
        <li>
            <a href="~/Content/Hinhtaixe/@item.CHANDUNG" target="_blank"><img src="~/Content/Hinhtaixe/@item.CHANDUNG" class="avatar" alt="Avatar"></a>
            <div class="message_date">
                <h3 class="date text-info">@item.NGAYDI.Value.Day</h3>
                <p class="month"> Tháng @item.NGAYDI.Value.Month</p>
            </div>
            <div class="message_wrapper">
                <h4 class="heading">@item.HOTENTX</h4>
                <blockquote class="message">@item.LOTRINHDI (@item.SOKMDI KM). @item.LOTRINHVE (@item.SOKMVE KM)</blockquote>
                <br />
            </div>
        </li>

    </ul>
}

QuanLyXe/Views/Xe/Thongkethang.cshtml
<br />
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	theme: "light2", // "light1", "light2", "dark1", "dark2"
	title: {
		text: "Thống kê tháng: @ViewBag.thang"
	},
	axisY: {
		title: "Số KM"
	},
	data: [{
		type: "column",
		dataPoints: @Html.Raw(ViewBag.DataPoints)
	}]
});
chart.render();

}
</script>

<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<br />
<h2>Số chuyến đi trong tháng @ViewBag.thang/@ViewBag.nam: @ViewBag.sochuyen chuyến</h2>
<h2>Số KM đã đi trong tháng @ViewBag.thang/@ViewBag.nam: @ViewBag.sokm KM</h2>
<br />

<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

QuanLyXe/Views/Xe/ThongtinPhikhac.cshtml
@model IEnumerable<QuanLyXe.Models.PHIKHAC>

<h3>Phí khác</h3>
<table class="data table table-striped no-margin">
    <thead>
        <tr>
            <th>Địa điểm</th>
            <th>Nội dung</th>
            <th>Tổng tiền</th>
            <th>Ngày thực hiện</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>@item.NOITHUCHIEN</td>
                <td>@item.NOIDUNGPHI</td>
                <td>@item.TONGPHI</td>
                <td>@item.NGAYTHUCHIEN.Value.Day/@item.NGAYTHUCHIEN.Value.Month/@item.NGAYTHUCHIEN.Value.Year</td>
            </tr>
        }
    </tbody>
</table>

QuanLyXe/Views/Xe/ThongtinSuachua.cshtml
@model IEnumerable<QuanLyXe.Models.v_Suachua>

<h3>Sửa chữa</h3>
<table class="data table table-striped no-margin">
    <thead>
        <tr>
            <th>Nơi sửa</th>
            <th>Nội dung</th>
            <th>Số lượng</th>
            <th>Tổng tiền</th>
            <th>Ngày bắt đầu</th>
            <th>Ngày kết thúc</th>
            <th>Ghi chú</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>@item.NOISUA</td>
                <td>@item.NOIDUNGSC</td>
                <td>@item.SOLUONGSC</td>
                <td>@item.TONGTIENSC</td>
                <td>@item.NGAYBD.Value.Day/@item.NGAYBD.Value.Month/@item.NGAYBD.Value.Year</td>
                <td>@item.NGAYKT.Value.Day/@item.NGAYKT.Value.Month/@item.NGAYKT.Value.Year</td>
                <td>@item.GHICHUSC</td>
            </tr>
        }
    </tbody>
</table>
<hr />